ALTER TABLE UE DROP CONSTRAINT fk_ue_semestre;
ALTER TABLE EC DROP CONSTRAINT fk_ec_ue;
ALTER TABLE Note DROP CONSTRAINT fk_note_etudiant;
ALTER TABLE Note DROP CONSTRAINT fk_note_ec;
ALTER TABLE Resultat DROP CONSTRAINT fk_resultat_etudiant;
ALTER TABLE Resultat DROP CONSTRAINT fk_resultat_semestre;


DROP TABLE Note CASCADE CONSTRAINTS;
DROP TABLE Resultat CASCADE CONSTRAINTS;
DROP TABLE EC CASCADE CONSTRAINTS;
DROP TABLE UE CASCADE CONSTRAINTS;
DROP TABLE Etudiant CASCADE CONSTRAINTS;
DROP TABLE Semestre CASCADE CONSTRAINTS;
